sony/nnabla-rl

README.md

I fixed build badge url of readme. The current url indicates a wrong url.

Fix build badge URL

---

interactive-demos/atari.ipynb
interactive-demos/atari_install.sh
interactive-demos/colab_utils.py
interactive-demos/pendulum.ipynb
interactive-demos/tutorial-algorithm.ipynb
interactive-demos/tutorial-envs.ipynb
interactive-demos/tutorial-model.ipynb
interactive-demos/tutorial-replay-buffer.ipynb
interactive-demos/tutorial-solver.ipynb

I fixed notebooks used in google colaboratory.
Current notebooks can't use RenderHook because it can't import interactive-demos/colab_utils.py.
And I fixed them for enabling to choose GPU mode as default setting.

Fix interactive-demos used in colab.

---

README.md

Fixing typo in readme. Seemless -> Seamless

Fix typo seemless -> seamless

---

nnabla_rl/functions.py
tests/test_functions.py

Adding triangular matrix function.
This function computes (lower/upper) triangular matrix L or U from two components, diagonal and non diagonal.
Triangular matrix is used in RL algorithms such as [NAF](https://arxiv.org/abs/1603.00748) and [MPO](https://arxiv.org/pdf/1806.06920.pdf) and would be useful to implement these algorithms.

Add triangular matrix function

---

docs/source/nnablarl_api.rst
docs/source/nnablarl_api/parametric_functions.rst
nnabla_rl/initializers.py
nnabla_rl/parametric_functions.py
tests/test_initializers.py
tests/test_parametric_functions.py

Implementation of [Noisy net](https://arxiv.org/abs/1706.10295).
Noisy net is used in several reinforcement learning algorithms including [Rainbow](https://arxiv.org/abs/1710.02298)

Add noisy net implementation

---

nnabla_rl/algorithms/__init__.py
nnabla_rl/algorithms/categorical_ddqn.py
nnabla_rl/model_trainers/q_value/__init__.py
nnabla_rl/model_trainers/q_value/categorical_ddqn_q_trainer.py
tests/algorithms/test_categorical_ddqn.py

Add categorical double dqn.
Categorical double dqn is almost same as categorical dqn but computes q value distribution alike double dqn.
Categorical double dqn is used in [Rainbow](https://arxiv.org/abs/1710.02298) algorithm.

Add categorical double dqn

---

docs/source/nnablarl_api/functions.rst

Fixed the docs typo that had caused sphinx build error.

Fix docs typo

---

nnabla_rl/parametric_functions.py

Fixed spatial softmax docstrings. The fixed result is like

Fix spatial softmax docstring

---

nnabla_rl/functions.py
tests/test_functions.py

Add stop gradient function. This is convenient compared to setting need_grad flag to False in below case.
```python
x.need_grad = False
y = function1(x)
z = function2(x)
```
```python
x_with_grad = x
x_no_grad = stop_gradient(x_with_grad) 
y = function1(x_no_grad)
z = function2(x_with_grad)
```

Add stop gradient function

---

.gitignore
bin/insert_copyright

Use gitignore to exclude directories from copyright insertion script.

Read gitignore and exclude ignore files from copyright insertion

---

nnabla_rl/algorithms/ppo.py
tests/algorithms/test_ppo.py
tests/distributions/test_one_hot_softmax.py

Run PPO on single process when actor num configuration is set to 1.
This prevents creating redundant process which may decrease machine performance.

Run PPO on single process when actor num is 1

---

nnabla_rl/model_trainers/policy/demme_policy_trainer.py
nnabla_rl/model_trainers/policy/soft_policy_trainer.py
nnabla_rl/model_trainers/q_value/value_distribution_function_trainer.py

Some training script was using incorrect training_variables when unrolling the network graph.
This PR will fix this issue.

Correct variable to use during rnn training

---

nnabla_rl/external/atari_wrappers.py

I am not sure when this change was made but in some environment, gym.unwrapped.np_random returns Generator instead of RandomState. 
```py
gym.unwrapped.np_random.rand_int(...)
gym.unwrapped.np_random.integers(...)
```
This PR will fix this issue and chooses correct function for sampling integers.

Check np_random instance and use correct randint alternative

---

.github/workflows/build.yml

Change build timelimit to 5 minutes to avoid unexpected stops during testing

Extend github build timelimit to 5 minutes

---

nnabla_rl/distributions/distribution.py
nnabla_rl/distributions/gaussian.py
nnabla_rl/distributions/gmm.py
nnabla_rl/model_trainers/encoder/kld_variational_auto_encoder_trainer.py
nnabla_rl/models/classic_control/policies.py
nnabla_rl/numpy_model_trainers/__init__.py
nnabla_rl/numpy_model_trainers/distribution_parameters/__init__.py
nnabla_rl/numpy_model_trainers/distribution_parameters/gmm_parameter_trainer.py
nnabla_rl/numpy_model_trainers/numpy_model_trainer.py
nnabla_rl/numpy_models/distribution_parameter.py
nnabla_rl/numpy_models/distribution_parameters/__init__.py
nnabla_rl/numpy_models/distribution_parameters/gmm_parameter.py
tests/algorithms/test_ppo.py
tests/distributions/test_gaussian.py
tests/distributions/test_gmm.py
tests/model_trainers/test_policy_trainers.py
tests/numpy_model_trainers/__init__.py
tests/numpy_model_trainers/distribution_parameters/test_gmm_parameter_trainer.py
tests/numpy_models/__init__.py
tests/numpy_models/distribution_parameters/__init__.py
tests/numpy_models/distribution_parameters/test_gmm_parameter.py
tests/test_functions.py

Added gmm and gaussian of the numpy models.
In addition, updated the gaussian distribution's API.
The API change is like following:
Previous :
```py
batch_size = 10
output_dim = 10
input_shape = (batch_size, output_dim)
mean = np.zeros(shape=input_shape)
sigma = np.ones(shape=input_shape) * 5.
ln_var = np.log(sigma) * 2.
distribution = D.Gaussian(mean, ln_var)
assert isinstance(distribution.sample(), nn.Variable)
```
Updated:
```py
batch_size = 10
output_dim = 10
input_shape = (batch_size, output_dim)
mean = np.zeros(shape=input_shape)
sigma = np.ones(shape=input_shape) * 5.
ln_var = np.log(sigma) * 2.
distribution = D.Gaussian(nn.Variable.from_numpy_array(mean), nn.Variable.from_numpy_array(ln_var))
assert isinstance(distribution.sample(), nn.Variable)
distribution = D.Gaussian(mean[0], …
```

Add gmm and Update gaussian

---

nnabla_rl/environment_explorers/gaussian_explorer.py
tests/environment_explorers/test_gaussian.py

The Gaussian explorer's np.clip was not functioning as expected when using the default value of action_clip_low.
Because the sys.finfo.min does not represent the minimum value of the float types.
This PR fixes this issue by assigning the correct minimum as the default.

Fix float max/min value range of gaussian explorer

---

nnabla_rl/algorithms/a2c.py
nnabla_rl/algorithms/ppo.py
nnabla_rl/distributions/bernoulli.py
nnabla_rl/distributions/softmax.py
tests/algorithms/test_common_utils.py

Fix test code errors due to the update of numpy packages
Fix np.int deprecation errors
Fix non terminal's shape on test

Fixing testing code errors

---

nnabla_rl/environments/dummy.py

gym's Envspec uses different arg names among different versions and causes error.
(around ver. 0.23.0. id is named as id_requested)
This PR fixes this issue by passing the id without specifying its name.

Pass id as positional arg to avoid unexpected error on old gym

---

.github/workflows/deploy.yml
deploy_requirements.txt

Use [Trusted Publisher](https://docs.pypi.org/trusted-publishers/) method when uploading to pypi.

Fix pypi deploy workflow and use OIDC

---

.github/workflows/build.yml
README.md
nnabla_rl/environments/wrappers/hybrid_env.py
setup.cfg

Remove python 3.7 from supporting python version and add 3.10

Remove python 3.7 support and add 3.10 support

---

nnabla_rl/algorithms/ppo.py
tests/algorithms/test_ppo.py

Fix the PPO tuple support bug.
More specifically, fill_result method of PPO actor does not work when state is tuple.

Fix ppo tuple support

---

nnabla_rl/writers/file_writer.py
test_resources/writers/evaluation_results_scalar%.3f.tsv
test_resources/writers/evaluation_results_scalar%.5f.tsv
test_resources/writers/evaluation_results_scalar%f.tsv
tests/writers/test_file_writer.py

Added format specifier to enable saving more digits to file.

Add format specifier to file writer

---

nnabla_rl/__init__.py
nnabla_rl/model_trainers/policy/amp_policy_trainer.py

Update dev version to 0.16.0

---

.github/workflows/build.yml
nnabla_rl/model_trainers/v_value/v_function_trainer.py

This PR is for fixing the following github actions errros.
The error is caused by black installation.
From version 24.10.0, black dropped python3.8 supports.
To solve this, I used python `3.9` in `build.yaml`
With the new version of mypy, the test for typing fails.
The solution is to use `0.0` not `0` in `v_function_model_trainer`.
The error message is
```
nnabla_rl/model_trainers/v_value/v_function_trainer.py:127: error: Incompatible types in assignment (expression has type "Union[float, Any]", variable has type "int")  [assignment]
```

Fix github actions error

---

nnabla_rl/utils/misc.py
tests/utils/test_misc.py

create_variables was not supporting tuple shaped variables and raises error when tuple shaped variables are requested.
This PR fixes this issue and properly supports tuple shaped variables in create_variables.

Support creating variables with tuple states
