interactive-demos/tutorial-algorithm.ipynb
I fixed bug of interactive-demo code about gpu id.
=> Fix interactive-demos used in colab about gpu id.

CONTRIBUTING.md, README.md, docs/source/conf.py, docs/source/index.rst, docs/source/nnablarl_api.rst, nnabla_rl/initializers.py, reproductions/mujoco/ddpg/README.md, tests/distributions/test_gaussian.py, tests/distributions/test_squashed_gaussian.py
I update the project name to nnablaRL.
=> Update NNablaRL to nnablaRL

nnabla_rl/algorithms/gail.py, nnabla_rl/algorithms/icml2015_trpo.py, nnabla_rl/algorithms/reinforce.py, nnabla_rl/algorithms/trpo.py
I fixed docstring of algorithms.
Current docstring will produce wrong documentations.
=> Fix docstring of algorithms

nnabla_rl/__init__.py
Updating development version for next release
=> Update development version

docs/source/nnablarl_api.rst, docs/source/nnablarl_api/functions.rst, nnabla_rl/functions.py
Adding documentation of each function defined in nnabla_rl.functions.
=> Add function docs

nnabla_rl/algorithm.py, nnabla_rl/environment_explorer.py, nnabla_rl/environment_explorers/epsilon_greedy_explorer.py, nnabla_rl/environment_explorers/gaussian_explorer.py, nnabla_rl/environment_explorers/raw_policy_explorer.py, nnabla_rl/model_trainers/encoder/kld_variational_auto_encoder_trainer.py, nnabla_rl/model_trainers/model_trainer.py, nnabla_rl/model_trainers/policy/a2c_policy_trainer.py, nnabla_rl/model_trainers/policy/bear_policy_trainer.py, nnabla_rl/model_trainers/policy/dpg_policy_trainer.py, nnabla_rl/model_trainers/policy/ppo_policy_trainer.py, nnabla_rl/model_trainers/policy/soft_policy_trainer.py, nnabla_rl/model_trainers/policy/spg_policy_trainer.py, nnabla_rl/model_trainers/policy/trpo_policy_trainer.py, nnabla_rl/model_trainers/q_value/quantile_distribution_function_trainer.py, nnabla_rl/model_trainers/q_value/squared_td_q_function_trainer.py, nnabla_rl/model_trainers/q_value/state_action_quantile_function_trainer.py, nnabla_rl/model_trainers/q_value/value_distribution_function_trainer.py, nnabla_rl/model_trainers/reward/gail_reward_function_trainer.py, nnabla_rl/model_trainers/v_value/squared_td_v_function_trainer.py, nnabla_rl/replay_buffer.py, nnabla_rl/typing.py
This PR is for fixing mypy typing of numpy array to np.ndarray.
np.array is a function so np.ndarray is more suitable in this case.
=> Fix numpy array typing to np.ndarray

docs/source/conf.py
Fixed release version to display correct package version in read the docs.
=> Display correct version

docs/source/nnablarl_api/functions.rst, nnabla_rl/functions.py, tests/test_functions.py
Add batch wise flatten function.
This is useful when extracting features using CNN and feed extracted features to FF networks.
=> Add batch_flatten function

docs/source/nnablarl_api.rst, docs/source/nnablarl_api/builders.rst, docs/source/nnablarl_api/environment_explorers.rst, nnabla_rl/algorithms/categorical_ddqn.py, nnabla_rl/algorithms/categorical_dqn.py, nnabla_rl/algorithms/ddpg.py, nnabla_rl/algorithms/dqn.py, nnabla_rl/algorithms/gail.py, nnabla_rl/algorithms/icml2015_trpo.py, nnabla_rl/algorithms/icml2018_sac.py, nnabla_rl/algorithms/iqn.py, nnabla_rl/algorithms/munchausen_dqn.py, nnabla_rl/algorithms/munchausen_iqn.py, nnabla_rl/algorithms/qrdqn.py, nnabla_rl/algorithms/reinforce.py, nnabla_rl/algorithms/sac.py, nnabla_rl/algorithms/td3.py, nnabla_rl/algorithms/trpo.py, nnabla_rl/builders/__init__.py, nnabla_rl/builders/explorer_builder.py, nnabla_rl/environment_explorers/epsilon_greedy_explorer.py, nnabla_rl/environment_explorers/gaussian_explorer.py, nnabla_rl/environment_explorers/raw_policy_explorer.py
Enable providing environment explorer from outside of an Algorithm through ExplorerBuilder.
=> Enable injecting explorer to algorithm

nnabla_rl/algorithms/common_utils.py, tests/algorithms/test_common_utils.py
Updated the function, compute_v_target_and_advantage, to support tuple state.
=> Fix compute_v_target_and_advantage to support tuple state

nnabla_rl/algorithms/bcq.py, nnabla_rl/algorithms/bear.py, nnabla_rl/algorithms/categorical_dqn.py, nnabla_rl/algorithms/ddpg.py, nnabla_rl/algorithms/dqn.py, nnabla_rl/algorithms/icml2018_sac.py, nnabla_rl/algorithms/munchausen_dqn.py, nnabla_rl/algorithms/sac.py, nnabla_rl/algorithms/td3.py, nnabla_rl/replay_buffer.py, nnabla_rl/replay_buffers/__init__.py, nnabla_rl/replay_buffers/memory_efficient_atari_buffer.py, nnabla_rl/replay_buffers/prioritized_replay_buffer.py, nnabla_rl/utils/data.py, tests/replay_buffers/test_memory_efficient_atari_buffer.py, tests/replay_buffers/test_prioritized_replay_buffer.py
Adding rank-based version of prioritized buffer and bugfixes of prioritized replay implementations.
=> Add rank-based prioritized replay and bugfixes

docs/source/nnablarl_api/parametric_functions.rst, nnabla_rl/parametric_functions.py, tests/test_parametric_functions.py
Added spatial softmax function proposed in https://arxiv.org/abs/1509.06113.
=> Add spatial softmax

bin/evaluate_algorithm
Fix algorithm reproduction directory path
=> Fix algorithm reproduction directory path

reproductions/algorithms/mujoco/ddpg/README.md, reproductions/algorithms/mujoco/icml2015trpo/README.md, reproductions/algorithms/mujoco/icml2018sac/README.md, reproductions/algorithms/mujoco/ppo/README.md, reproductions/algorithms/mujoco/sac/README.md, reproductions/algorithms/mujoco/td3/README.md, reproductions/algorithms/mujoco/trpo/README.md
Fixed readme typo in the mujoco reproduction.
=> Fix readme of reproduction

tests/test_functions.py
Increased initial variance value of cross entropy methods tests and decreased tolerance for avoiding the test errors.
=> Fix cem test

.readthedocs.yaml, README.md
Added readthedocs.yaml file to specify the python version for building the docs.
Updated README.md to notice the build error much easier.
=> Add readthedocs yaml

.readthedocs.yaml, docs/source/nnablarl_api/algorithms.rst, docs/source/nnablarl_api/environment_explorers.rst, nnabla_rl/algorithm.py, nnabla_rl/environment_explorers/epsilon_greedy_explorer.py, nnabla_rl/environment_explorers/gaussian_explorer.py, nnabla_rl/environment_explorers/raw_policy_explorer.py, nnabla_rl/functions.py, nnabla_rl/models/model.py, requirements.txt
=> Fix sphinx build warnings

nnabla_rl/algorithms/ddpg.py, nnabla_rl/algorithms/her.py, nnabla_rl/algorithms/sac.py, nnabla_rl/algorithms/td3.py
Add n-step Q learning support for actor-critic algorithms such as:
- DDPG
- TD3
- HER
- SAC
=> Support n-step q learning in ddpg, td3, her and sac

nnabla_rl/algorithms/README.md
Add HER and IQN to algorithm catalog.
=> Fix Algorithm catalog

bin/insert_copyright
Exclude .venv directory from copyright insertion search directory.
=> Exclude .venv dir from copyright insertion

nnabla_rl/algorithms/README.md, nnabla_rl/algorithms/ddqn.py, nnabla_rl/algorithms/dqn.py, nnabla_rl/algorithms/drqn.py, nnabla_rl/algorithms/munchausen_dqn.py, nnabla_rl/model_trainers/q_value/squared_td_q_function_trainer.py, tests/algorithms/test_dqn.py, tests/algorithms/test_drqn.py
Add RNN support to following algorithms.
- DQN
- Double DQN
- M-DQN
=> Support RNN models on DQN and DQN inherited algorithms

nnabla_rl/algorithms/README.md, nnabla_rl/algorithms/categorical_ddqn.py, nnabla_rl/algorithms/categorical_dqn.py, nnabla_rl/algorithms/common_utils.py, nnabla_rl/algorithms/ddpg.py, nnabla_rl/algorithms/dqn.py, nnabla_rl/algorithms/icml2018_sac.py, nnabla_rl/algorithms/iqn.py, nnabla_rl/algorithms/munchausen_iqn.py, nnabla_rl/algorithms/qrdqn.py, nnabla_rl/algorithms/rainbow.py, nnabla_rl/algorithms/sac.py, nnabla_rl/algorithms/td3.py, nnabla_rl/model_trainers/policy/trpo_policy_trainer.py, nnabla_rl/model_trainers/q_value/iqn_q_trainer.py, nnabla_rl/model_trainers/q_value/quantile_distribution_function_trainer.py, nnabla_rl/model_trainers/q_value/state_action_quantile_function_trainer.py, nnabla_rl/model_trainers/q_value/value_distribution_function_trainer.py, nnabla_rl/models/distributional_function.py, nnabla_rl/models/model.py, nnabla_rl/parametric_functions.py, reproductions/algorithms/atari/rainbow/rainbow_reproduction.py, tests/algorithms/test_categorical_dqn.py, tests/algorithms/test_iqn.py, tests/algorithms/test_qrdqn.py, tests/test_parametric_functions.py
Add RNN layer support to the following algorithms
- Categorical DQN/DDQN
- Rainbow
- QRDQN
- IQN
- M-IQN
=> Expand RNN support to dist rl algorithms

nnabla_rl/algorithms/README.md, nnabla_rl/algorithms/atrpo.py, nnabla_rl/algorithms/common_utils.py, nnabla_rl/algorithms/ddpg.py, nnabla_rl/algorithms/gail.py, nnabla_rl/algorithms/her.py, nnabla_rl/algorithms/icml2018_sac.py, nnabla_rl/algorithms/ppo.py, nnabla_rl/algorithms/sac.py, nnabla_rl/algorithms/td3.py, nnabla_rl/algorithms/trpo.py, nnabla_rl/model_trainers/policy/dpg_policy_trainer.py, nnabla_rl/model_trainers/policy/soft_policy_trainer.py, nnabla_rl/model_trainers/v_value/soft_v_trainer.py, nnabla_rl/model_trainers/v_value/squared_td_v_function_trainer.py, nnabla_rl/preprocessors/her_preprocessor.py, nnabla_rl/utils/misc.py, tests/algorithms/test_common_utils.py, tests/algorithms/test_ddpg.py, tests/algorithms/test_her.py, tests/algorithms/test_icml2018_sac.py, tests/algorithms/test_sac.py, tests/algorithms/test_td3.py
Added RNN model support to the following algorithms
- DDPG
- HER
- SAC/ICML2018SAC
- TD3
=> Add rnn support to actor critic algorithms

nnabla_rl/algorithms/icml2018_sac.py, tests/algorithms/test_icml2018_sac.py
Add n-step q training support to icml2018 version of soft actor critic
=> Add n-step q support to ICML2018SAC

nnabla_rl/algorithms/a2c.py, nnabla_rl/algorithms/atrpo.py, nnabla_rl/algorithms/bcq.py, nnabla_rl/algorithms/bear.py, nnabla_rl/algorithms/common_utils.py, nnabla_rl/algorithms/gail.py, nnabla_rl/algorithms/icml2015_trpo.py, nnabla_rl/algorithms/ppo.py, nnabla_rl/algorithms/reinforce.py, nnabla_rl/algorithms/trpo.py, tests/algorithms/test_common_utils.py
Enable computing evaluation actions from batched states.
=> Support batched states for evaluation

README.md, nnabla_rl/algorithm.py, nnabla_rl/utils/reproductions.py, reproductions/algorithms/atari/a2c/README.md, reproductions/algorithms/atari/ddqn/README.md, reproductions/algorithms/atari/drqn/README.md, reproductions/algorithms/atari/icml2015trpo/README.md, reproductions/algorithms/atari/iqn/README.md, reproductions/algorithms/atari/munchausen_dqn/README.md, reproductions/algorithms/atari/munchausen_iqn/README.md, reproductions/algorithms/atari/ppo/README.md, reproductions/algorithms/atari/qrdqn/README.md, reproductions/algorithms/atari/rainbow/README.md, setup.cfg
Fix README.md sample and add clarified prerequisites of Atari reproduction codes.
=> Fix README samples and add prerequisites for Atari reproduction codes

docs/source/nnablarl_api/distributions.rst, nnabla_rl/distributions/__init__.py, nnabla_rl/distributions/bernoulli.py, tests/distributions/test_bernoulli.py
Add Bernoulli distribution. This distribution is almost same as softmax distribution but has only 1 class.
=> Add Bernoulli distribution

nnabla_rl/distributions/softmax.py, tests/distributions/test_softmax.py
Improve softmax distribution and support sampling from multidimensional logits.
=> Enable sampling from multidimensional logits

docs/source/nnablarl_api/distributions.rst, nnabla_rl/distributions/__init__.py, nnabla_rl/distributions/one_hot_softmax.py, nnabla_rl/distributions/softmax.py, tests/distributions/test_one_hot_softmax.py
Add one-hot softmax distribution.
This distribution samples an one-hot vector instead of class index.
Backend distribution is same as softmax function.
=> Add one hot softmax

interactive-demos/tutorial-model.ipynb
Fix argument variable name (algorithm_params -> algorithm_config) and change hyper parameter for training.
=> Fix tutorial-model

docs/source/nnablarl_api/functions.rst, nnabla_rl/functions.py, tests/test_functions.py
Implemented random shooting function.
=> Add random shooting

requirements.txt, setup.cfg
Workaround fix. Support only gym < 0.22.0 and avoid GoalEnv error.
=> Fix add workaround to avoid gym error.

nnabla_rl/functions.py, nnabla_rl/replay_buffers/hindsight_replay_buffer.py, tests/test_functions.py
Updated interface of cross entropy function methods.
The args, pop_size is now changed to sample_size.
In addition, the given objective function to CEM function will be called with variable x which has (batch_size, sample_size, x_dim).
This is different from previous interface. If you want to know the details, please see the function docs.
=> Update cem function interface

nnabla_rl/utils/debugging.py
=> Add profile function

nnabla_rl/__init__.py
Increment dev version for the next release
=> increment dev version

nnabla_rl/algorithms/atrpo.py, nnabla_rl/algorithms/drqn.py, nnabla_rl/utils/solver_wrappers.py, tests/utils/test_solver_wrappers.py
Fix ATRPO and DRQN.
Properly apply grad clip and weight decay.
=> Fix algos. Properly apply grad clip and weight decay

nnabla_rl/algorithms/sac.py
Fixing typo in the pydoc of SAC algorithm.
=> Fix module path of sac

nnabla_rl/algorithms/common_utils.py, tests/algorithms/test_common_utils.py
Updated to support discrete tuple.
Now, it's possible to use the DiscreteTuple Env in nnablaRL !!
=> Update to support discrete tuple

nnabla_rl/algorithms/ppo.py, tests/algorithms/test_ppo.py
Updated PPO to support tuple state.
=> Add PPO tuple state support

nnabla_rl/algorithm.py, nnabla_rl/algorithms/bcq.py, nnabla_rl/algorithms/ddpg.py, nnabla_rl/algorithms/her.py, nnabla_rl/algorithms/td3.py, nnabla_rl/environment_explorer.py, nnabla_rl/environments/dummy.py, nnabla_rl/environments/environment_info.py, nnabla_rl/environments/gym_utils.py, nnabla_rl/environments/wrappers/common.py, nnabla_rl/environments/wrappers/goal_conditioned.py, nnabla_rl/environments/wrappers/mujoco.py, nnabla_rl/external/goal_env.py, nnabla_rl/model_trainers/policy/her_policy_trainer.py, reproductions/algorithms/mujoco/her/README.md, reproductions/algorithms/mujoco/her/her_reproduction.py, requirements.txt, setup.cfg
Add GoalEnv module in order to use the latest version of gym.
=> Add goal_env module

docs/source/nnablarl_api/algorithms.rst, nnabla_rl/algorithm.py, nnabla_rl/algorithms/README.md, nnabla_rl/algorithms/__init__.py, nnabla_rl/algorithms/ilqr.py, nnabla_rl/algorithms/lqr.py, nnabla_rl/numpy_models/__init__.py, nnabla_rl/numpy_models/cost_function.py, nnabla_rl/numpy_models/dynamics.py, nnabla_rl/numpy_models/numpy_model.py, reproductions/algorithms/classic_control/ilqr/README.md, reproductions/algorithms/classic_control/ilqr/ilqr_acrobot.py, reproductions/algorithms/classic_control/ilqr/ilqr_pendulum.py, reproductions/algorithms/classic_control/lqr/lqr_cartpole.py, tests/algorithms/test_ilqr.py, tests/algorithms/test_lqr.py
Implementation of Linear Quadratic Regulator (LQR) and iterative LQR algorithms.
Co-authored-by: Yu Ishihara <yu.ishihara@sony.com>
Co-authored-by: Shunichi Sekiguchi <shunichi.sekiguchi@sony.com>
=> Add iLQR and LQR

nnabla_rl/environments/wrappers/common.py, requirements.txt, setup.cfg
This is a bug fix to support new gym interface since gym ver.0.25.0.
=> Fix ScreenRenderEnv to support gym 0.25.0

.github/workflows/build.yml, .github/workflows/deploy.yml, README.md, nnabla_rl/environments/wrappers/goal_conditioned.py, nnabla_rl/model_trainers/policy/soft_policy_trainer.py, requirements.txt, setup.cfg, tests/replay_buffers/test_hindsight_replay_buffer.py
Remove python 3.6 support and add python 3.9 support.
[nnabla does not support python 3.6 anymore](https://github.com/sony/nnabla/releases/tag/v1.26.0)
=> Only support python 3.7 or greater

nnabla_rl/__init__.py
Update development version to 0.13.0.dev1 for next release's development
=> Update dev version to v0.13.0.dev1

interactive-demos/colab_utils.py, interactive-demos/package_install.sh, interactive-demos/pendulum.ipynb, interactive-demos/tutorial-algorithm.ipynb, interactive-demos/tutorial-model.ipynb, interactive-demos/tutorial-replay-buffer.ipynb, interactive-demos/tutorial-solver.ipynb
Fix colab notebook.
- Update nnabla-ext-cuda version to nnabla-ext-cuda114
- Comment out ScreenRenderEnv on colab
=> Fix colab notebook

interactive-demos/package_install.sh, nnabla_rl/environments/wrappers/goal_conditioned.py
Install pygame when running on colab
=> Add pygame installation for colab demos

docs/source/nnablarl_api/hooks.rst, nnabla_rl/algorithm.py, nnabla_rl/hook.py, nnabla_rl/hooks/__init__.py, nnabla_rl/hooks/progress_bar_hook.py, nnabla_rl/logger.py, requirements.txt, setup.cfg
Added progress bar hook which is for supporting tqdm bar.
Co-authored-by: Yu Ishihara <yu.ishihara@sony.com>
=> Add progress bar hook

nnabla_rl/typing.py, tests/test_typing.py
Added a decorator for checking the input shape of a function.
=> Add accepted shape decorator

nnabla_rl/algorithms/reinforce.py, nnabla_rl/distributions/squashed_gaussian.py, nnabla_rl/external/atari_wrappers.py, nnabla_rl/functions.py, nnabla_rl/models/distributional_function.py, nnabla_rl/models/model.py, nnabla_rl/models/mujoco/reward_functions.py, nnabla_rl/models/reward_function.py, nnabla_rl/typing.py, nnabla_rl/utils/optimization.py, reproductions/algorithms/pybullet/icra2018qtopt/external_grasping_env/kuka_grasping_procedural_env.py
Applied docformatter to some files for solving the error of github actions.
=> Apply docformatter

nnabla_rl/__init__.py, reproductions/algorithms/pybullet/icra2018qtopt/external_grasping_env/kuka_grasping_procedural_env.py
Update development version to 0.14.0.dev1 for next release's development.
=> Update dev version to v0.14.0.dev1

examples/evaluate_trained_model.py, examples/training_example.py, examples/writer_example.py
Fixing deprecation error when using PendulumEnv on example codes
=> Fix Deprecation error when using PendulumEnv

nnabla_rl/environments/environment_info.py, tests/environments/test_env_info.py
Add supports for environments with tupled states that have both discrete and continuous state.
=> Support mixed (discrete and continuous) state env

nnabla_rl/environment_explorer.py
Add begin_of_episode to enable using this info when sampling warmup actions.
=> Add begin_of_episode to warmup_action

nnabla_rl/__init__.py, nnabla_rl/models/pybullet/q_functions.py
=> Update dev version to 0.15.0

requirements.txt
To fix the error due to mypy's bug, I changed requirements.txt not to use mypy 1.11.0
See [this post](https://github.com/python/mypy/issues/17542)
=> Fix test error due to mypy's bug

.readthedocs.yaml
Fixed a documentation build error caused by using setuptools.
=> Update readthedocs yaml

README.md
Added isort badge to README.md
=> Add isort badge

nnabla_rl/utils/data.py, tests/utils/test_data.py
Added support for marshaling tupled info elements
=> Add support for info elements with tuple values
